[tools]
"http:cicd-engineering" = { version = "0.9.1", url = "https://github.com/nicodes/cicd/releases/download/v{{ version }}/cicd-engineering-v{{ version }}.tar.gz", checksum = "sha256:98fab8c33a93b2140f240eacf6bf29026f3aac4615979c627cde64b02a21a396" }
actionlint = "1.7.12"
shellcheck = "0.11.0"
python = "3.13.11"

bun = "1.4.1"
