[tools]
"http:cicd-engineering" = { version = "0.11.0", url = "https://github.com/nicodes/tools/releases/download/v{{ version }}/cicd-engineering-v{{ version }}.tar.gz", checksum = "sha256:220b7681d0515fabdf3e6a397818f64a2d99dadbdb03eab703907c921bd69dea" }
actionlint = "1.7.12"
shellcheck = "0.11.0"
python = "3.13.11"

bun = "1.4.1"
