[tools]
"http:cicd-engineering" = { version = "0.9.0", url = "https://github.com/nicodes/cicd/releases/download/v{{ version }}/cicd-engineering-v{{ version }}.tar.gz", checksum = "sha256:d9f61a682b9e306b609aa2371693a8e76c4ce90b474d3e8769f69771c9213c66" }
actionlint = "1.7.12"
shellcheck = "0.11.0"
python = "3.13.11"

bun = "1.4.1"
