#!/usr/bin/env python3
"""check-secrets/check.py - the portfolio's secret rule, as a check.

THE RULE, in one sentence: a secret is held in GitHub and delivered to the host
by komizo, or it is generated on the host and never leaves it -- and there is no
third way.

Spelled out, because each clause is a mistake somebody already made:

  1. Secrets live in GitHub. Every one the host needs is named
     KOMIZO_SECRET_<NAME> on the deploy step, which is both the declaration and
     the delivery -- set-secrets pushes each as <NAME> into the host's
     write-only secrets.env.

  2. What CANNOT be held in GitHub is generated on the host and stays there:
     the PostgreSQL superuser password and the role passwords derived from it.
     They reach a container through host-local files -- postgres-owner.env, and
     the per-service files under secrets/current that the scoped-env profile
     provisions. Nobody types them and nothing in CI has ever seen them.

  3. Nothing else writes the host's secret store. No scp of an env file, no
     `ssh host 'cat >> secrets.env'`, no calling set-secret-<app> by hand. A
     value placed that way has no provenance: it is not in GitHub, it was not
     generated by a profile, and the only record that it exists is the file.

  4. secrets.env is ONE file holding EVERY GitHub secret, so a service that
     reads it reads all of them. Only the service that needs them may. This is
     the check that would have caught the Revik near-miss: flattening all four
     services onto secrets.env would have handed the API the migrator DSN --
     the credential that can drop the schema -- in the name of simplifying the
     deploy.

  5. No secret value is ever committed. A key in compose.yml is a key in the
     registry image, in every clone, and in the reflog after it is "removed".

WHAT THIS CANNOT SEE. A repository is only half the system; the other half is
what is actually on the box. A key removed from cd.yml is not removed from the
host -- set-secret writes and never deletes -- so the file outlives the
workflow that put it there. `--host-keys` closes that half: give it the key
names read off the host and it reports both directions of the drift. CI has no
host access, so that mode is for the operator script, not the deploy.

Exit 0 when the rule holds, 1 when it does not. Every failure names the file
and what to do about it.
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    # Same reasoning as publish-config/parse-config.py: this repository does not
    # pip install at deploy time. Every GitHub-hosted runner ships PyYAML.
    print(
        "::error::PyYAML is required. GitHub-hosted runners ship it; on a "
        "self-hosted runner install python3-yaml.",
        file=sys.stderr,
    )
    sys.exit(1)


# Secret-shaped literals. Deliberately a short list of things that are secret by
# construction rather than a generic entropy guess: a false positive here blocks
# a merge, and the check people route around is worth nothing. Publishable keys
# (pk_live_, pk_test_) are absent on purpose -- they are meant to be in the
# client bundle, and flagging them is how a check earns a blanket ignore.
SECRET_SHAPES = [
    (re.compile(r"\bsk_(live|test)_[A-Za-z0-9]{8,}"), "a Clerk/Stripe secret key"),
    (re.compile(r"\bwhsec_[A-Za-z0-9]{8,}"), "a webhook signing secret"),
    (re.compile(r"\b(?:AKIA|ASIA)[A-Z0-9]{16}\b"), "an AWS access key id"),
    (re.compile(r"\bgh[pousr]_[A-Za-z0-9]{16,}"), "a GitHub token"),
    (re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"), "a private key"),
    (re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}"), "a Slack token"),
    # A DSN carrying a password. The password has to look like a value rather
    # than a placeholder, so ${...} interpolation and the empty password pass.
    (
        re.compile(r"\b[a-z][a-z0-9+.-]*://[A-Za-z0-9_.-]+:(?!\s*\$)[^\s:@/${}]{6,}@"),
        "a connection string with a password in it",
    ),
]

# Ways to reach the host's secret store that are not set-secrets. Matched
# against the workflow text, which is why they are written as the shapes a
# workflow actually contains rather than as parsed steps: the point is that
# NOTHING here writes secrets.env, however it is spelled.
BYPASS_SHAPES = [
    (re.compile(r"set-secret-[A-Za-z0-9_-]+"), "calls the host's set-secret command directly"),
    (re.compile(r"secrets\.env"), "names the host's secrets.env"),
    (re.compile(r"\bscp\b"), "copies a file to the host with scp"),
]


class Findings:
    """Collect every violation before exiting, so one run lists them all.

    A check that stops at the first failure turns a five-minute fix into five
    round trips through CI.
    """

    def __init__(self):
        self.errors = []
        self.notes = []

    def error(self, where, message):
        self.errors.append(f"{where}: {message}")

    def note(self, message):
        self.notes.append(message)

    def report(self):
        for note in self.notes:
            print(f"note: {note}")
        for error in self.errors:
            print(f"::error::{error}", file=sys.stderr)
        if self.errors:
            print(
                f"\n{len(self.errors)} violation(s) of the secret rule. "
                "See komizo-actions/docs/secrets.md.",
                file=sys.stderr,
            )
            return 1
        print("secret rule: ok")
        return 0


def load_compose(path, findings):
    """Parse the compose file far enough to see who reads which env file.

    Not `docker compose config`: that resolves every env_file, which means the
    file has to exist, which means CI would need stand-ins for the host-local
    files -- and standing in for a secret file is the thing being checked. The
    question here is textual anyway: which paths are named, by which service.
    """
    try:
        doc = yaml.safe_load(Path(path).read_text()) or {}
    except (OSError, yaml.YAMLError) as exc:
        findings.error(path, f"could not be read as YAML: {exc}")
        return {}
    services = doc.get("services")
    if not isinstance(services, dict):
        findings.error(path, "has no services: mapping")
        return {}
    return services


def normalise(path):
    """Strip one leading "./" and nothing else.

    `lstrip("./")` strips CHARACTERS, not a prefix: it turns
    "../secrets/current/api.env" into "secrets/current/api.env", which matches
    the scoped-env prefix and passes. A path that climbs out of the app
    directory is exactly the case this checker exists for, so it must survive
    normalisation intact and be judged on what it says.
    """
    while path.startswith("./"):
        path = path[2:]
    return path


def env_files(service):
    """The env_file entries of one service, in either form Compose allows.

    Compose accepts a string, a list of strings, and a list of
    {path:, required:} mappings. A checker that understands only the list form
    reads the other two as "this service has no env_file" -- which is a pass,
    and the wrong answer.
    """
    raw = service.get("env_file")
    if raw is None:
        return []
    if isinstance(raw, str):
        raw = [raw]
    paths = []
    for entry in raw:
        if isinstance(entry, dict):
            entry = entry.get("path")
        if isinstance(entry, str):
            paths.append(normalise(entry))
    return paths


def parse_allowlist(values, findings):
    """`path: service[,service]` lines -> {path: {services}}.

    Host-local secret files are named one at a time, with the services allowed
    to read them, so adding a fifth reader to postgres-owner.env is a diff in
    the workflow rather than a line in a compose file nobody reviews.
    """
    allowed = {}
    for value in values:
        value = value.strip()
        if not value or value.startswith("#"):
            continue
        if ":" not in value:
            findings.error("host-only", f"{value!r} is not 'path: service[,service]'")
            continue
        path, services = value.split(":", 1)
        allowed[normalise(path.strip())] = {
            s.strip() for s in services.split(",") if s.strip()
        }
    return allowed


def check_no_committed_secrets(paths, findings):
    """Rule 5. A secret in a tracked file is already published."""
    for path in paths:
        try:
            text = Path(path).read_text()
        except OSError:
            continue  # a missing file is reported by whoever needed it
        for number, line in enumerate(text.splitlines(), 1):
            for shape, what in SECRET_SHAPES:
                if shape.search(line):
                    findings.error(
                        f"{path}:{number}",
                        f"looks like {what}, committed. Move it to a GitHub "
                        "secret and deliver it as KOMIZO_SECRET_<NAME>, then "
                        "rotate it -- it is in the history either way.",
                    )
                    break


def check_delivery(workflow, findings):
    """Rules 1 and 2: what the workflow declares, and how.

    Returns the set of names delivered, which the drift check compares against
    the host.
    """
    try:
        text = Path(workflow).read_text()
    except OSError as exc:
        findings.error(workflow, f"could not be read: {exc}")
        return set()

    delivered = set()
    # The declaration is the env: line itself -- `KOMIZO_SECRET_X: <expr>` --
    # so name and value are checked together. Read line by line rather than
    # through the YAML parser because a workflow is also checked for the shapes
    # below, and those live in `run:` blocks as text.
    for number, line in enumerate(text.splitlines(), 1):
        match = re.match(r"\s*KOMIZO_SECRET_([A-Z0-9_]+)\s*:\s*(.*?)\s*$", line)
        if not match:
            continue
        name, value = match.group(1), match.group(2).strip().strip("\"'")
        delivered.add(name)
        if not re.fullmatch(r"\$\{\{\s*secrets\.[A-Za-z0-9_]+\s*\}\}", value):
            if re.fullmatch(r"\$\{\{\s*vars\.[A-Za-z0-9_]+\s*\}\}", value):
                findings.note(
                    f"{workflow}:{number}: {name} is delivered from a repository "
                    "variable, so its value is public. That is fine for a "
                    "nonsecret, but it does not need the secret store."
                )
                continue
            findings.error(
                f"{workflow}:{number}",
                f"KOMIZO_SECRET_{name} must be a ${{{{ secrets.NAME }}}} "
                f"expression; got {value!r}. A literal here is a committed "
                "secret, and a computed value has no record of what was sent.",
            )

    if not delivered:
        findings.note(
            f"{workflow} delivers no secrets. Correct for an app that needs "
            "none; suspicious for one whose host has keys (see --host-keys)."
        )

    # Rule 3. Confined to run: blocks -- the env: lines above legitimately
    # contain the string set-secrets, and the deploy action's own `uses:` line
    # names the directory.
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if stripped.startswith(("uses:", "- uses:", "#")):
            continue
        if re.match(r"\s*KOMIZO_SECRET_", line):
            continue
        for shape, what in BYPASS_SHAPES:
            if shape.search(line):
                findings.error(
                    f"{workflow}:{number}",
                    f"{what}. The host's secret store is written by the "
                    "set-secrets action and by nothing else; a value placed "
                    "any other way has no provenance.",
                )
                break
    return delivered


def check_readers(services, scoped_dir, host_only, secrets_env_readers, findings):
    """Rules 2 and 4: every env_file is accounted for, and secrets.env is not shared."""
    readers = []
    for name, service in sorted(services.items()):
        if not isinstance(service, dict):
            continue
        for path in env_files(service):
            if ".." in Path(path).parts:
                findings.error(
                    f"{name}",
                    f"reads env_file {path!r}, which climbs out of the app "
                    "directory. What it resolves to depends on where the host "
                    "happens to run compose from, so nobody can say which "
                    "file this is.",
                )
            elif path == "secrets.env":
                readers.append(name)
            elif scoped_dir and path.startswith(scoped_dir.rstrip("/") + "/"):
                continue  # host-local, provisioned by the scoped-env profile
            elif path in host_only:
                if name not in host_only[path]:
                    findings.error(
                        f"{name}",
                        f"reads {path}, which is host-local and declared for "
                        f"{', '.join(sorted(host_only[path])) or 'no service'}. "
                        "Host-local credentials are the ones CI has never seen; "
                        "widening who reads them is a deliberate change.",
                    )
            else:
                findings.error(
                    f"{name}",
                    f"reads env_file {path!r}, which is neither secrets.env "
                    f"(delivered from GitHub), nor under {scoped_dir or '(unset)'} "
                    "(provisioned on the host), nor declared in host-only. "
                    "Every secret has one of those two origins; this file has "
                    "neither, so nothing says where its values came from.",
                )

    if secrets_env_readers:
        unexpected = set(readers) - secrets_env_readers
        missing = secrets_env_readers - set(readers)
        for name in sorted(unexpected):
            findings.error(
                name,
                "reads secrets.env but is not in secrets-env-services. That "
                "file holds EVERY secret this app keeps in GitHub, so this "
                "service now receives all of them.",
            )
        for name in sorted(missing):
            findings.error(
                "secrets-env-services",
                f"names {name}, which reads no secrets.env. Either the service "
                "was renamed or the delivery is going nowhere.",
            )
    elif len(readers) > 1:
        findings.error(
            "deploy/compose.yml",
            f"{len(readers)} services read secrets.env ({', '.join(readers)}). "
            "It holds every secret this app keeps in GitHub, so each of them "
            "receives all of them. Split the ones that differ into host-local "
            "per-service files, or pass secrets-env-services to say that "
            "sharing is intended.",
        )


def check_drift(delivered, host_keys_path, findings):
    """The half a repository cannot see: what is actually on the box.

    set-secret writes and never deletes, so removing a name from cd.yml leaves
    the value on the host indefinitely. Extra keys are the interesting
    direction: each one is either a credential nobody is rotating or a
    hand-placed value, and both are the thing this rule exists to prevent.
    """
    try:
        text = Path(host_keys_path).read_text()
    except OSError as exc:
        findings.error(host_keys_path, f"could not be read: {exc}")
        return
    host = {
        line.strip().split("=", 1)[0]
        for line in text.splitlines()
        if line.strip() and not line.strip().startswith("#")
    }
    host.discard("")
    for name in sorted(host - delivered):
        findings.error(
            "host secrets.env",
            f"{name} is on the host but no workflow delivers it. It was placed "
            "by hand or left behind by a workflow that no longer sets it; "
            "either way nothing rotates it. Add it to the deploy step, or "
            "remove it from the host and rotate it at its provider.",
        )
    for name in sorted(delivered - host):
        findings.note(
            f"{name} is delivered by CI but is not on the host yet -- expected "
            "if it was added since the last deploy."
        )


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Check an app against the komizo secret rule.",
    )
    parser.add_argument("--compose", required=True, help="path to the compose file")
    parser.add_argument(
        "--workflow",
        required=True,
        action="append",
        help="path to a deploy workflow; repeat for preview and production",
    )
    parser.add_argument(
        "--scoped-env-dir",
        default="secrets/current",
        help="prefix marking a host-local per-service env file (default: secrets/current)",
    )
    parser.add_argument(
        "--host-only",
        default=[],
        action="append",
        metavar="PATH:SERVICE[,SERVICE]",
        help="a host-local secret file and the services allowed to read it",
    )
    parser.add_argument(
        "--secrets-env-services",
        default="",
        help="comma-separated services that may read secrets.env (default: at most one)",
    )
    parser.add_argument(
        "--host-keys",
        default="",
        help="file of key names read off the host, to check for drift",
    )
    args = parser.parse_args(argv)

    findings = Findings()
    host_only = parse_allowlist(args.host_only, findings)
    readers = {s.strip() for s in args.secrets_env_services.split(",") if s.strip()}

    check_no_committed_secrets([args.compose, *args.workflow], findings)
    delivered = set()
    for workflow in args.workflow:
        delivered |= check_delivery(workflow, findings)
    services = load_compose(args.compose, findings)
    if services:
        check_readers(services, args.scoped_env_dir, host_only, readers, findings)
    if args.host_keys:
        check_drift(delivered, args.host_keys, findings)
    return findings.report()


if __name__ == "__main__":
    sys.exit(main())
